model:
  arch:
    n_nodes: 1
    n_wires: 4
    node_archs:
      - n_wires: 4
        encoder_op_list_name: 4x4_ryzxy
        n_blocks: 3
        n_layers_per_block: 3
        q_layer_name: barren_0
    down_sample_kernel_size: 6
    act_norm: null
    pruning_method: gradient_based_pruning
    accumulation_window_size: 1
    pruning_window_size: 2
    pruning_ratio: 0.5
  name: q_multifc0
  transpile_before_run: False
  load_op_list: False

dataset:
  input_name: image
  target_name: digit

optimizer:
  name: adam
  lr: 5e-2
  weight_decay: 1.0e-4
  lambda_lr: 1.e-2

run:
  n_epochs: 15
  bsz: 25
  workers_per_gpu: 8
  device: gpu

debug:
  pdb: False
  set_seed: True
  seed: 42

callbacks:
  - callback: 'InferenceRunner'
    split: 'valid'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/valid'
      - metrics: 'NLLError'
        name: 'loss/valid'
  - callback: 'InferenceRunner'
    split: 'test'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/test'
      - metrics: 'NLLError'
        name: 'loss/test'
  - callback: 'MaxSaver'
    name: 'acc/valid'
  - callback: 'Saver'
    max_to_keep: 10

qiskit:
  use_qiskit: True
  use_real_qc: False
  use_qiskit_train: True
  use_qiskit_valid: True
  backend_name: null
  noise_model_name: null
  basis_gates_name: null
  n_shots: 8192
  initial_layout: null
  seed_transpiler: 42
  seed_simulator: 42
  optimization_level: 0
  est_success_rate: False
  max_jobs: 1
