dataset:
  name: vqe
  input_name: input
  target_name: target
trainer:
  name: params_shift_trainer
run:
  steps_per_epoch: 10
  workers_per_gpu: 8
  n_epochs: 10
  bsz: 1
  device: gpu
model:
  transpile_before_run: False
  load_op_list: False
  hamil_filename: ../h2.txt
  arch:
    n_wires: 2
    n_layers_per_block: 2
    q_layer_name: seth_0
    n_blocks: 2
  name: vqe_0
qiskit:
  use_qiskit: False
  use_qiskit_train: True
  use_qiskit_valid: True
  use_real_qc: False
  backend_name: ibmq_quito
  noise_model_name: None
  n_shots: 8192
  initial_layout: None
  optimization_level: 0
  max_jobs: 1
ckpt:
  load_ckpt: False
  load_trainer: False
  name: checkpoints/min-loss-valid.pt
debug:
  pdb: False
  set_seed: False
optimizer:
  name: adam
  lr: 5e-2
  weight_decay: 1.0e-4
  lambda_lr: 1.e-2
criterion:
  name: minimize
scheduler:
  name: cosine
callbacks:
  - callback: 'InferenceRunner'
    split: 'valid'
    subcallbacks:
      - metrics: 'MinError'
        name: 'loss/valid'
  - callback: 'MinSaver'
    name: 'loss/valid'
  - callback: 'Saver'
    max_to_keep: 10
regularization:
  unitary_loss: False
legalization:
  legalize: False
